const BASE = "https://shanehead.github.io/brewski";

export const DOCS = {
  gettingStarted: `${BASE}/getting-started/what-is-brewski`,
  firstRecipe: `${BASE}/getting-started/first-recipe`,
  firstBatch: `${BASE}/getting-started/first-batch`,
  fermentables: `${BASE}/guides/fermentables`,
  hops: `${BASE}/guides/hops`,
  yeast: `${BASE}/guides/yeast`,
  mash: `${BASE}/guides/mash`,
  waterChemistry: `${BASE}/guides/water-chemistry`,
  scaling: `${BASE}/guides/scaling`,
  recipeVersions: `${BASE}/guides/recipe-versions`,
  brewDay: `${BASE}/guides/brew-day`,
  gravityTracking: `${BASE}/guides/gravity-tracking`,
  carbonation: `${BASE}/guides/carbonation`,
  ingredientLibrary: `${BASE}/guides/ingredient-library`,
  cloudSync: `${BASE}/guides/cloud-sync`,
  equipmentProfiles: `${BASE}/reference/equipment-profiles`,
  settings: `${BASE}/reference/settings`,
  beerxml: `${BASE}/reference/beerxml`,
  calcAbv: `${BASE}/reference/calculators/abv-calories`,
  calcHydrometer: `${BASE}/reference/calculators/hydrometer-correction`,
  calcRefractometer: `${BASE}/reference/calculators/refractometer`,
  calcGravity: `${BASE}/reference/calculators/gravity-conversions`,
  calcColor: `${BASE}/reference/calculators/color-conversions`,
  calcPitchRate: `${BASE}/reference/calculators/pitch-rate`,
  calcCarbonation: `${BASE}/reference/calculators/carbonation`,
  calcUnits: `${BASE}/reference/calculators/unit-conversions`,
  conceptGravity: `${BASE}/concepts/gravity`,
  conceptIbu: `${BASE}/concepts/ibu`,
  conceptColor: `${BASE}/concepts/color`,
  conceptHopForms: `${BASE}/concepts/hop-forms`,
  conceptPitchRate: `${BASE}/concepts/pitch-rate-starters`,
  conceptWaterIons: `${BASE}/concepts/water-ions`,
  faq: `${BASE}/faq`,
} as const;
