//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "batches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_version_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub brew_date: Option<i32>,
    pub fermenter_date: Option<i32>,
    pub conditioning_date: Option<i32>,
    pub packaging_date: Option<i32>,
    pub actual_pre_boil_volume_l: Option<f64>,
    pub actual_post_boil_volume_l: Option<f64>,
    pub actual_batch_size_l: Option<f64>,
    pub actual_pre_boil_gravity: Option<f64>,
    pub actual_og: Option<f64>,
    pub actual_fg: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub rating: Option<i32>,
    pub packaging_temp_c: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub carbonation_sugar_type: Option<String>,
    pub priming_sugar_g: Option<f64>,
    pub serving_pressure_kpa: Option<f64>,
    pub created_at: i32,
    pub updated_at: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::batch_gravity_readings::Entity")]
    BatchGravityReadings,
    #[sea_orm(
        belongs_to = "super::recipe_versions::Entity",
        from = "Column::RecipeVersionId",
        to = "super::recipe_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RecipeVersions,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::RecipeId",
        to = "super::recipes::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Recipes,
}

impl Related<super::batch_gravity_readings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BatchGravityReadings.def()
    }
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
