//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "equipment_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub boil_size_l: f64,
    pub batch_size_l: f64,
    pub calc_boil_volume: i32,
    pub tun_volume_l: Option<f64>,
    pub tun_weight_kg: Option<f64>,
    pub tun_specific_heat: Option<f64>,
    pub lauter_deadspace_l: Option<f64>,
    pub top_up_kettle_l: Option<f64>,
    pub trub_chiller_loss_l: Option<f64>,
    pub evap_rate_pct_hr: Option<f64>,
    pub boil_time_min: f64,
    pub top_up_water_l: Option<f64>,
    pub fermenter_loss_l: Option<f64>,
    pub hop_utilization_pct: Option<f64>,
    pub efficiency_pct: f64,
    pub created_at: i32,
    pub updated_at: i32,
    #[sea_orm(column_type = "Text")]
    pub batch_volume_target: String,
    pub mash_tun_loss_l: f64,
    pub hlt_deadspace_l: Option<f64>,
    pub cooling_shrinkage_pct: f64,
    pub calc_mash_efficiency: i32,
    pub mash_efficiency_pct: Option<f64>,
    pub calc_aroma_hop_utilization: i32,
    pub aroma_hop_utilization_pct: f64,
    pub whirlpool_time_min: Option<f64>,
    pub altitude_adjustment: i32,
    pub boil_temp_f: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub sparge_method: String,
    pub mash_volume_min_l: Option<f64>,
    pub mash_volume_max_l: Option<f64>,
    pub sparge_volume_min_l: Option<f64>,
    pub sparge_volume_max_l: Option<f64>,
    pub calc_strike_water_temp: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
