//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "equipment_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub boil_size_l: Decimal,
    pub batch_size_l: Decimal,
    pub calc_boil_volume: i32,
    pub tun_volume_l: Option<Decimal>,
    pub tun_weight_kg: Option<Decimal>,
    pub tun_specific_heat: Option<Decimal>,
    pub lauter_deadspace_l: Option<Decimal>,
    pub top_up_kettle_l: Option<Decimal>,
    pub trub_chiller_loss_l: Option<Decimal>,
    pub evap_rate_pct_hr: Option<Decimal>,
    pub boil_time_min: Decimal,
    pub top_up_water_l: Option<Decimal>,
    pub fermenter_loss_l: Option<Decimal>,
    pub hop_utilization_pct: Option<Decimal>,
    pub efficiency_pct: Decimal,
    pub created_at: i32,
    pub updated_at: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
