//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fermentables")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub yield_pct: Decimal,
    pub color_lovibond: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub origin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub supplier: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub add_after_boil: Option<i32>,
    pub coarse_fine_diff_pct: Option<Decimal>,
    pub moisture_pct: Option<Decimal>,
    pub diastatic_power_lintner: Option<Decimal>,
    pub protein_pct: Option<Decimal>,
    pub max_in_batch_pct: Option<Decimal>,
    pub recommend_mash: Option<i32>,
    pub ibu_gal_per_lb: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_addition_fermentables::Entity")]
    RecipeAdditionFermentables,
}

impl Related<super::recipe_addition_fermentables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionFermentables.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
