//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hops")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub alpha_pct: Decimal,
    pub beta_pct: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub form: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub origin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub year: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub substitutes: Option<String>,
    pub hsi_pct: Option<Decimal>,
    pub humulene_pct: Option<Decimal>,
    pub caryophyllene_pct: Option<Decimal>,
    pub cohumulone_pct: Option<Decimal>,
    pub myrcene_pct: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_addition_hops::Entity")]
    RecipeAdditionHops,
}

impl Related<super::recipe_addition_hops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionHops.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
