//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mash_steps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub mash_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub infuse_amount_l: Option<Decimal>,
    pub step_temp_c: Decimal,
    pub step_time_min: i32,
    pub ramp_time_min: Option<i32>,
    pub end_temp_c: Option<Decimal>,
    pub step_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::mashes::Entity",
        from = "Column::MashId",
        to = "super::mashes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Mashes,
}

impl Related<super::mashes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mashes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
