//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod equipment_profiles;
pub mod fermentables;
pub mod hops;
pub mod mash_steps;
pub mod mashes;
pub mod miscs;
pub mod recipe_addition_fermentables;
pub mod recipe_addition_hops;
pub mod recipe_addition_miscs;
pub mod recipe_addition_waters;
pub mod recipe_addition_yeasts;
pub mod recipe_water_adjustments;
pub mod recipes;
pub mod settings;
pub mod styles;
pub mod waters;
pub mod yeasts;
