//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub brewer: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub asst_brewer: Option<String>,
    pub batch_size_l: f64,
    pub boil_size_l: f64,
    pub boil_time_min: f64,
    pub efficiency_pct: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub equipment_profile_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub style_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub taste_notes: Option<String>,
    pub taste_rating: Option<f64>,
    pub og: Option<f64>,
    pub fg: Option<f64>,
    pub fermentation_stages: Option<i32>,
    pub primary_age_days: Option<f64>,
    pub primary_temp_c: Option<f64>,
    pub secondary_age_days: Option<f64>,
    pub secondary_temp_c: Option<f64>,
    pub tertiary_age_days: Option<f64>,
    pub tertiary_temp_c: Option<f64>,
    pub age_days: Option<f64>,
    pub age_temp_c: Option<f64>,
    pub carbonation_vols: Option<f64>,
    pub forced_carbonation: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub priming_sugar_name: Option<String>,
    pub carbonation_temp_c: Option<f64>,
    pub priming_sugar_equiv: Option<f64>,
    pub keg_priming_factor: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub date: Option<String>,
    pub created_at: i32,
    pub updated_at: i32,
    #[sea_orm(column_type = "Text")]
    pub mash_water_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub sparge_water_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::equipment_profiles::Entity",
        from = "Column::EquipmentProfileId",
        to = "super::equipment_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    EquipmentProfiles,
    #[sea_orm(has_one = "super::mashes::Entity")]
    Mashes,
    #[sea_orm(has_many = "super::recipe_addition_fermentables::Entity")]
    RecipeAdditionFermentables,
    #[sea_orm(has_many = "super::recipe_addition_hops::Entity")]
    RecipeAdditionHops,
    #[sea_orm(has_many = "super::recipe_addition_miscs::Entity")]
    RecipeAdditionMiscs,
    #[sea_orm(has_many = "super::recipe_addition_waters::Entity")]
    RecipeAdditionWaters,
    #[sea_orm(has_many = "super::recipe_addition_yeasts::Entity")]
    RecipeAdditionYeasts,
    #[sea_orm(has_many = "super::recipe_water_adjustments::Entity")]
    RecipeWaterAdjustments,
    #[sea_orm(
        belongs_to = "super::styles::Entity",
        from = "Column::StyleId",
        to = "super::styles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Styles,
    #[sea_orm(
        belongs_to = "super::waters::Entity",
        from = "Column::SpargeWaterId",
        to = "super::waters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Waters2,
    #[sea_orm(
        belongs_to = "super::waters::Entity",
        from = "Column::MashWaterId",
        to = "super::waters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Waters1,
}

impl Related<super::equipment_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EquipmentProfiles.def()
    }
}

impl Related<super::mashes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Mashes.def()
    }
}

impl Related<super::recipe_addition_fermentables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionFermentables.def()
    }
}

impl Related<super::recipe_addition_hops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionHops.def()
    }
}

impl Related<super::recipe_addition_miscs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionMiscs.def()
    }
}

impl Related<super::recipe_addition_waters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionWaters.def()
    }
}

impl Related<super::recipe_addition_yeasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionYeasts.def()
    }
}

impl Related<super::recipe_water_adjustments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeWaterAdjustments.def()
    }
}

impl Related<super::styles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Styles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
