//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_version_miscs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_version_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub misc_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub r#use: String,
    pub amount: f64,
    pub amount_is_weight: Option<i32>,
    pub time_min: f64,
    pub addition_order: i32,
    #[sea_orm(column_type = "Text")]
    pub unit: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::miscs::Entity",
        from = "Column::MiscId",
        to = "super::miscs::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Miscs,
    #[sea_orm(
        belongs_to = "super::recipe_versions::Entity",
        from = "Column::RecipeVersionId",
        to = "super::recipe_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RecipeVersions,
}

impl Related<super::miscs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Miscs.def()
    }
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
