//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_addition_hops")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub recipe_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub hop_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub alpha_pct: Decimal,
    #[sea_orm(column_type = "Text")]
    pub form: String,
    pub amount_kg: Decimal,
    #[sea_orm(column_type = "Text")]
    pub r#use: String,
    pub time_min: Decimal,
    pub addition_order: i32,
    pub whirlpool_temp_c: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hops::Entity",
        from = "Column::HopId",
        to = "super::hops::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hops,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::RecipeId",
        to = "super::recipes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recipes,
}

impl Related<super::hops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hops.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
