//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_id: String,
    pub version_number: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub brewer: Option<String>,
    pub batch_size_l: f64,
    pub boil_size_l: f64,
    pub boil_time_min: f64,
    pub efficiency_pct: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub style_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mash_water_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sparge_water_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub og: Option<f64>,
    pub fg: Option<f64>,
    pub primary_age_days: Option<f64>,
    pub primary_temp_c: Option<f64>,
    pub secondary_age_days: Option<f64>,
    pub secondary_temp_c: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub asst_brewer: Option<String>,
    pub fermentation_stages: Option<i32>,
    pub tertiary_age_days: Option<f64>,
    pub tertiary_temp_c: Option<f64>,
    pub age_days: Option<f64>,
    pub age_temp_c: Option<f64>,
    pub forced_carbonation: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub priming_sugar_name: Option<String>,
    pub carbonation_temp_c: Option<f64>,
    pub priming_sugar_equiv: Option<f64>,
    pub keg_priming_factor: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub equipment_profile_id: Option<String>,
    pub carbonation_vols: Option<f64>,
    pub created_at: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub parent_version_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::batches::Entity")]
    Batches,
    #[sea_orm(has_many = "super::recipe_version_fermentables::Entity")]
    RecipeVersionFermentables,
    #[sea_orm(has_many = "super::recipe_version_hops::Entity")]
    RecipeVersionHops,
    #[sea_orm(has_one = "super::recipe_version_mash::Entity")]
    RecipeVersionMash,
    #[sea_orm(has_many = "super::recipe_version_miscs::Entity")]
    RecipeVersionMiscs,
    #[sea_orm(has_many = "super::recipe_version_water_adjustments::Entity")]
    RecipeVersionWaterAdjustments,
    #[sea_orm(has_many = "super::recipe_version_waters::Entity")]
    RecipeVersionWaters,
    #[sea_orm(has_many = "super::recipe_version_yeasts::Entity")]
    RecipeVersionYeasts,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentVersionId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::RecipeId",
        to = "super::recipes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recipes,
}

impl Related<super::batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Batches.def()
    }
}

impl Related<super::recipe_version_fermentables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionFermentables.def()
    }
}

impl Related<super::recipe_version_hops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionHops.def()
    }
}

impl Related<super::recipe_version_mash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionMash.def()
    }
}

impl Related<super::recipe_version_miscs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionMiscs.def()
    }
}

impl Related<super::recipe_version_water_adjustments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionWaterAdjustments.def()
    }
}

impl Related<super::recipe_version_waters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionWaters.def()
    }
}

impl Related<super::recipe_version_yeasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionYeasts.def()
    }
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
