//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_version_fermentables")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_version_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub fermentable_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub yield_pct: f64,
    pub color_lovibond: f64,
    pub amount_kg: f64,
    pub add_after_boil: Option<i32>,
    pub addition_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fermentables::Entity",
        from = "Column::FermentableId",
        to = "super::fermentables::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fermentables,
    #[sea_orm(
        belongs_to = "super::recipe_versions::Entity",
        from = "Column::RecipeVersionId",
        to = "super::recipe_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RecipeVersions,
}

impl Related<super::fermentables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fermentables.def()
    }
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
