//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_addition_yeasts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub yeast_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub form: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub laboratory: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub product_id: Option<String>,
    pub attenuation_pct: Option<f64>,
    pub amount: Option<f64>,
    pub amount_is_weight: Option<i32>,
    pub add_to_secondary: Option<i32>,
    pub times_cultured: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::RecipeId",
        to = "super::recipes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recipes,
    #[sea_orm(
        belongs_to = "super::yeasts::Entity",
        from = "Column::YeastId",
        to = "super::yeasts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Yeasts,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl Related<super::yeasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Yeasts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
