//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_version_mash_steps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_version_mash_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub infuse_amount_l: Option<f64>,
    pub step_temp_c: f64,
    pub step_time_min: i32,
    pub ramp_time_min: Option<i32>,
    pub end_temp_c: Option<f64>,
    pub step_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipe_version_mash::Entity",
        from = "Column::RecipeVersionMashId",
        to = "super::recipe_version_mash::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RecipeVersionMash,
}

impl Related<super::recipe_version_mash::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionMash.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
