//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_version_water_adjustments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_version_id: String,
    #[sea_orm(column_type = "Text")]
    pub addition: String,
    #[sea_orm(column_type = "Text")]
    pub target: String,
    pub amount: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipe_versions::Entity",
        from = "Column::RecipeVersionId",
        to = "super::recipe_versions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RecipeVersions,
}

impl Related<super::recipe_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
