//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe_addition_waters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub recipe_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub water_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub amount_l: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipes::Entity",
        from = "Column::RecipeId",
        to = "super::recipes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Recipes,
    #[sea_orm(
        belongs_to = "super::waters::Entity",
        from = "Column::WaterId",
        to = "super::waters::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Waters,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl Related<super::waters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Waters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
