//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "styles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub category_number: String,
    #[sea_orm(column_type = "Text")]
    pub style_letter: String,
    #[sea_orm(column_type = "Text")]
    pub style_guide: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub og_min: Decimal,
    pub og_max: Decimal,
    pub fg_min: Decimal,
    pub fg_max: Decimal,
    pub ibu_min: Decimal,
    pub ibu_max: Decimal,
    pub color_min_srm: Decimal,
    pub color_max_srm: Decimal,
    pub carb_min_vols: Option<Decimal>,
    pub carb_max_vols: Option<Decimal>,
    pub abv_min_pct: Option<Decimal>,
    pub abv_max_pct: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ingredients: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub examples: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipes::Entity")]
    Recipes,
}

impl Related<super::recipes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
