//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "waters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub calcium_ppm: Decimal,
    pub bicarbonate_ppm: Decimal,
    pub sulfate_ppm: Decimal,
    pub chloride_ppm: Decimal,
    pub sodium_ppm: Decimal,
    pub magnesium_ppm: Decimal,
    pub ph: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_addition_waters::Entity")]
    RecipeAdditionWaters,
}

impl Related<super::recipe_addition_waters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionWaters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
