//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "yeasts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub form: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub laboratory: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub product_id: Option<String>,
    pub min_temperature_c: Option<f64>,
    pub max_temperature_c: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flocculation: Option<String>,
    pub attenuation_pct: Option<f64>,
    pub min_attenuation_pct: Option<f64>,
    pub max_attenuation_pct: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub alcohol_tolerance: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flavor_profile: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub styles: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub substitutes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub species: Option<String>,
    pub pof_positive: Option<i32>,
    pub sta1_positive: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub best_for: Option<String>,
    pub max_reuse: Option<i32>,
    pub add_to_secondary: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipe_addition_yeasts::Entity")]
    RecipeAdditionYeasts,
    #[sea_orm(has_many = "super::recipe_version_yeasts::Entity")]
    RecipeVersionYeasts,
}

impl Related<super::recipe_addition_yeasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeAdditionYeasts.def()
    }
}

impl Related<super::recipe_version_yeasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipeVersionYeasts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
